### ISSUE TITLE
When going through Multiverse Portal, sends to spawn not saved location.

### ISSUE THREAD

**Issue by dragonism** [Taronyuu/StayPut#4]
I have recently setup a Multiverse portal to tp myself from "Hub" to "GGOP". Although, when going through the portal, its sends me to /spawn not my saved location.

Is there any way I can change it to tp me to my latest location from the other multiworld or is that a feature that has not been added yet?

Thanks.

**Comment by Taronyuu** [comment]
If you enable debugging in the config file you can see what is going on and possibly why you aren't being teleported back to your original location.

**Comment by Taronyuu** [comment]
Closing this until a reply has been made.
